name: Deploy mdBook til GitHub Pages

on:
  push:
    branches:
      - main  # Kun ved commits til main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installer mdBook (nyeste stabile version)
        run: |
          MDBOOK_VERSION=$(curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -L https://github.com/rust-lang/mdBook/releases/download/$MDBOOK_VERSION/mdbook-$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin

      - name: Installer Rust og Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Installer mdBook PDF og EPUB plugins
        run: |
          # Installer mdBook PDF
          cargo install mdbook-pdf --vers $(cargo search mdbook-pdf --limit 1 | grep -o "v[0-9.]*" | tr -d 'v')
          
          # Installer mdBook EPUB
          cargo install mdbook-epub --vers $(cargo search mdbook-epub --limit 1 | grep -o "v[0-9.]*" | tr -d 'v')

      - name: Installer afhængigheder for PDF-generering
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Byg mdBook (HTML, PDF og EPUB)
        run: |
          mdbook build  # Standard HTML build
          mdbook-pdf ./
          mdbook-epub ./

      - name: Flyt PDF og EPUB til book-mappen
        run: |
          mkdir -p ./book/downloads
          mv ./book.pdf ./book/downloads/
          mv ./book.epub ./book/downloads/

      - name: Publicer til GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book 